### ISSUE TITLE
ReferenceError: SchemaObject is not defined

### ISSUE THREAD

**Issue by xdliyushen** [LottieFiles/lottie-docs#40]
Hello!

I was trying to find unknown features, and got this as result:
```shell
/Users/liyushen/Documents/code/lottie-docs/docs/scripts/lottie_explain.js:1576
    module.exports = { SchemaData, SchemaObject };
                                   ^
ReferenceError: SchemaObject is not defined
    at Object.<anonymous> (/Users/liyushen/Documents/code/lottie-docs/docs/scripts/lottie_explain.js:1576:36)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/Users/liyushen/Documents/code/lottie-docs/tools/unknown_features.js:4:15)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)

Node.js v19.3.0
```
And my python virtual environment seems fine:
![截屏2022-12-21 14 30 48](https://user-images.githubusercontent.com/37898499/208837070-aa329260-9275-483c-b83f-881f6e97ec6e.png)
It seems like there is no `SchemaObject` in lottie_examplain.js. I wonder which part did I do is wrong and how to fix this?

**Comment by mbasaglia** [comment]
It used to be a class but got removed, I'm going to clean it up
